framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing.yml"
    session:
        save_path: "%kernel.cache_dir%/../../sessions/admin/%kernel.environment%"

# Doctrine Configuration
doctrine:
    orm:
        dql:
            string_functions:
                CAST: Sulu\Component\Rest\DQL\Cast

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/445
parameters:
    jms_serializer.identical_property_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
    jms_serializer.identical_property_naming_strategy:
        class: %jms_serializer.identical_property_naming_strategy.class%
        public: false

    sulu.serialized_naming_strategy:
        class: %jms_serializer.serialized_name_annotation_strategy.class%
        public: false
        arguments:
            - @jms_serializer.identical_property_naming_strategy

    jms_serializer.naming_strategy:
        alias: sulu.serialized_naming_strategy

# Massive Build Configuration
massive_build:
    targets:
        prod:
            dependencies:
                database: ~
                phpcr: ~
                fixtures: ~
                phpcr_migrations: ~
        dev:
            dependencies:
                database: ~
                fixtures: ~
                phpcr: ~
                user: ~
                phpcr_migrations: ~
        maintain:
            dependencies:
                node_order:
                search_index:
                phpcr_migrations: ~

# Sulu Bundles
sulu_admin:
    name: %sulu_admin.name%
    email: %sulu_admin.email%

sulu_contact:
    form_of_address:
        male:
            id: 0
            name: male
            translation: contact.contacts.formOfAddress.male
        female:
            id: 1
            name: female
            translation: contact.contacts.formOfAddress.female
