framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing.yml"
    session:
        save_path: "%kernel.cache_dir%/../../sessions/admin/%kernel.environment%"

# Doctrine Configuration
doctrine:
    orm:
        dql:
            string_functions:
                CAST: Sulu\Component\Rest\DQL\Cast

# Massive Build Configuration
massive_build:
    targets:
        prod:
            dependencies:
                database: ~
                phpcr: ~
                fixtures: ~
                phpcr_migrations: ~
        dev:
            dependencies:
                database: ~
                fixtures: ~
                phpcr: ~
                user: ~
                phpcr_migrations: ~
        maintain:
            dependencies:
                node_order:
                search_index:
                phpcr_migrations: ~

# Sulu Bundles
sulu_admin:
    name: %sulu_admin.name%
    email: %sulu_admin.email%

sulu_contact:
    form_of_address:
        male:
            id: 0
            name: male
            translation: contact.contacts.formOfAddress.male
        female:
            id: 1
            name: female
            translation: contact.contacts.formOfAddress.female
