imports:
    - { resource: ../../Resources/config/parameters.yml }
    - { resource: ../../Resources/config/phpcr.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ SuluAdminBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: xml
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false
        resolve_target_entities:
            Sulu\Component\Security\UserInterface: Sulu\Bundle\SecurityBundle\Entity\User
        dql:
            string_functions:
                CAST: Sulu\Component\Rest\DQL\Cast

stof_doctrine_extensions:
    orm:
        default:
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json

sulu_core:
    phpcr:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    webspace:
        config_dir: "%kernel.root_dir%/../Resources/webspaces"
        request_analyzer:
            enabled: false
    content:
        ~

sulu_content:
    preview:
        fallback:
            interval: %content_fallback_intervall%
        websocket:
            port: %content_preview_port%

sulu_admin:
    name: SULU 2.0

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

liip_theme:
    themes: ["default"]
    active_theme: "default"
    load_controllers: false
