sulu_security:
    resource: "@SuluSecurityBundle/Resources/config/routing.yml"
    prefix: /security

sulu_contact_:
    resource: "@SuluContactBundle/Resources/config/routing.yml"
    prefix: /contact

sulu_admin:
    resource: "@SuluAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sulu_translate:
    resource: "@SuluTranslateBundle/Resources/config/routing.yml"
    prefix: /translate