liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"
